const words = [
  "close",
  "chair",
  "sky",
  "boat",
  "clean",
  "soon",
  "bright",
  "slowly",
  "big",
  "no",
  "study",
  "new",
  "loud",
  "sad",
  "nowhere",
  "time",
  "water",
  "new",
  "inside",
  "work",
  "study",
  "blue",
  "inside",
  "new",
  "fast",
  "while",
  "city",
  "water",
  "time",
  "computer",
  "dark",
  "swim",
  "slow",
  "dirty",
  "cold",
  "boat",
  "though",
  "drink",
  "sadly",
  "slowly",
  "car",
  "work",
  "run",
  "music",
  "phone",
  "maybe",
  "dirty",
  "swim",
  "and",
  "listen",
  "sweet",
  "family",
  "sky",
  "fly",
  "small",
  "walk",
  "loud",
  "sometimes",
  "bright",
  "goodbye",
  "slow",
  "red",
  "quiet",
  "quickly",
  "close",
  "thank",
  "house",
  "walk",
  "dark",
  "sing",
  "dog",
  "study",
  "big",
  "clean",
  "movie",
  "movie",
  "sad",
  "but",
  "slow",
  "well",
  "walk",
  "bright",
  "study",
  "but",
  "drink",
  "drive",
  "well",
  "study",
  "river",
  "inside",
  "read",
  "red",
  "walk",
  "moon",
  "apple",
  "or",
  "hot",
  "slow",
  "fast",
  "star",
  "always",
  "inside",
  "music",
  "or",
  "sadly",
  "sad",
  "write",
  "just",
  "or",
  "quickly",
  "food",
  "boat",
  "drink",
  "fly",
  "old",
  "old",
  "outside",
  "close",
  "nowhere",
  "walk",
  "always",
  "moon",
  "close",
  "fly",
  "inside",
  "never",
  "well",
  "sad",
  "dog",
  "school",
  "learn",
  "moon",
  "phone",
  "everywhere",
  "fly",
  "downstairs",
  "dirty",
  "apple",
  "listen",
  "water",
  "computer",
  "sorry",
  "eat",
  "green",
  "friend",
  "food",
  "sky",
  "slowly",
  "bright",
  "sun",
  "plane",
  "just",
  "red",
  "happily",
  "close",
  "when",
  "boat",
  "boat",
  "new",
  "downstairs",
  "chair",
  "star",
  "school",
  "no",
  "just",
  "old",
  "sun",
  "slow",
  "just",
  "early",
  "if",
  "fly",
  "okay",
  "fly",
  "drive",
  "dog",
  "city",
  "water",
  "because",
  "train",
  "learn",
  "read",
  "work",
  "red",
  "house",
  "learn",
  "tree",
  "never",
  "maybe",
  "eat",
  "quickly",
  "phone",
  "sometimes",
  "dark",
  "friend",
  "and",
  "late",
  "train",
  "often",
  "just",
  "early",
  "tree",
  "tree",
  "house",
  "please",
  "bright",
  "upstairs",
  "though",
  "downstairs",
  "work",
  "family",
  "music",
  "apple",
  "city",
  "swim",
  "quiet",
  "time",
  "bright",
  "flower",
  "sad",
  "sun",
  "learn",
  "sleep",
  "while",
  "slow",
  "car",
  "read",
  "please",
  "car",
  "open",
  "sometimes",
  "sad",
  "well",
  "movie",
  "music",
  "music",
  "inside",
  "book",
  "early",
  "study",
  "red",
  "run",
  "but",
  "nowhere",
  "learn",
  "soon",
  "plane",
  "blue",
  "sad",
  "eat",
  "write",
  "okay",
  "sorry",
  "silently",
  "walk",
  "hello",
  "because",
  "though",
  "read",
  "sky",
  "food",
  "study",
  "school",
  "thank",
  "upstairs",
  "until",
  "bright",
  "cold",
  "late",
  "cold",
  "everywhere",
  "phone",
  "often",
  "train",
  "green",
  "upstairs",
  "friend",
  "nowhere",
  "loud",
  "listen",
  "run",
  "red",
  "sleep",
  "learn",
  "inside",
  "though",
  "well",
  "flower",
  "dirty",
  "if",
  "sadly",
  "train",
  "speak",
  "yes",
  "time",
  "because",
  "blue",
  "late",
  "never",
  "listen",
  "train",
  "and",
  "drive",
  "when",
  "well",
  "please",
  "if",
  "run",
  "clean",
  "bright",
  "cat",
  "train",
  "fast",
  "school",
  "often",
  "work",
  "school",
  "speak",
  "sadly",
  "but",
  "road",
  "swim",
  "sometimes",
  "late",
  "sorry",
  "food",
  "when",
  "always",
  "river",
  "yes",
  "late",
  "silently",
  "okay",
  "train",
  "train",
  "but",
  "dark",
  "inside",
  "cat",
  "maybe",
  "fast",
  "red",
  "sorry",
  "apple",
  "green",
  "tree",
  "computer",
  "downstairs",
  "read",
  "happily",
  "green",
  "slow",
  "bright",
  "early",
  "nowhere",
  "happy",
  "always",
  "blue",
  "jump",
  "learn",
  "never",
  "big",
  "slow",
  "no",
  "phone",
  "or",
  "open",
  "movie",
  "star",
  "red",
  "school",
  "outside",
  "loudly",
  "upstairs",
  "cold",
  "late",
  "downstairs",
  "blue",
  "dirty",
  "dog",
  "time",
  "please",
  "close",
  "goodbye",
  "no",
  "sing",
  "downstairs",
  "late",
  "tree",
  "thank",
  "movie",
  "soon",
  "school",
  "speak",
  "read",
  "city",
  "dirty",
  "please",
  "always",
  "happily",
  "late",
  "happy",
  "flower",
  "small",
  "tree",
  "maybe",
  "hello",
  "green",
  "yes",
  "big",
  "open",
  "everywhere",
  "speak",
  "slowly",
  "new",
  "dark",
  "city",
  "listen",
  "blue",
  "quiet",
  "outside",
  "road",
  "family",
  "dirty",
  "goodbye",
  "red",
  "quiet",
  "jump",
  "flower",
  "always",
  "phone",
  "eat",
  "quickly",
  "apple",
  "downstairs",
  "sometimes",
  "jump",
  "river",
  "walk",
  "sky",
  "if",
  "downstairs",
  "school",
  "always",
  "dog",
  "computer",
  "and",
  "but",
  "upstairs",
  "computer",
  "big",
  "speak",
  "green",
  "city",
  "sweet",
  "drink",
  "often",
  "nowhere",
  "eat",
  "maybe",
  "sadly",
  "write",
  "water",
  "swim",
  "loudly",
  "tree",
  "late",
  "learn",
  "clean",
  "quickly",
  "dirty",
  "green",
  "tree",
  "computer",
  "computer",
  "silently",
  "everywhere",
  "book",
  "but",
  "time",
  "drink",
  "slowly",
  "study",
  "movie",
  "please",
  "hello",
  "soon",
  "food",
  "car",
  "walk",
  "cat",
  "plane",
  "please",
  "moon",
  "train",
  "blue",
  "new",
  "upstairs",
  "train",
  "city",
  "tree",
  "sometimes",
  "sky",
  "jump",
  "just",
  "happily",
  "jump",
  "school",
  "sometimes",
  "star",
  "phone",
  "drive",
  "until",
  "just",
  "or",
  "loud",
  "moon",
  "happy",
  "quickly",
  "never",
  "red",
  "sing",
  "movie",
  "drink",
  "happy",
  "happily",
  "old",
  "dirty",
  "plane",
  "soon",
  "sweet",
  "big",
  "bird",
  "boat",
  "old",
  "learn",
  "clean",
  "work",
  "sorry",
  "chair",
  "cat",
  "time",
  "slow",
  "and",
  "blue",
  "well",
  "small",
  "star",
  "apple",
  "loud"
];

const countryFlagsImg = [
  {name: "afghanistan", code: "AF", url: "https://flagcdn.com/w320/af.png"},
  {name: "albania", code: "AL", url: "https://flagcdn.com/w320/al.png"},
  {name: "algeria", code: "DZ", url: "https://flagcdn.com/w320/dz.png"},
  {name: "andorra", code: "AD", url: "https://flagcdn.com/w320/ad.png"},
  {name: "angola", code: "AO", url: "https://flagcdn.com/w320/ao.png"},
  {name: "antigua-and-barbuda", code: "AG", url: "https://flagcdn.com/w320/ag.png"},
  {name: "argentina", code: "AR", url: "https://flagcdn.com/w320/ar.png"},
  {name: "armenia", code: "AM", url: "https://flagcdn.com/w320/am.png"},
  {name: "australia", code: "AU", url: "https://flagcdn.com/w320/au.png"},
  {name: "austria", code: "AT", url: "https://flagcdn.com/w320/at.png"},
  {name: "azerbaijan", code: "AZ", url: "https://flagcdn.com/w320/az.png"},
  {name: "bahamas", code: "BS", url: "https://flagcdn.com/w320/bs.png"},
  {name: "bahrain", code: "BH", url: "https://flagcdn.com/w320/bh.png"},
  {name: "bangladesh", code: "BD", url: "https://flagcdn.com/w320/bd.png"},
  {name: "barbados", code: "BB", url: "https://flagcdn.com/w320/bb.png"},
  {name: "belarus", code: "BY", url: "https://flagcdn.com/w320/by.png"},
  {name: "belgium", code: "BE", url: "https://flagcdn.com/w320/be.png"},
  {name: "belize", code: "BZ", url: "https://flagcdn.com/w320/bz.png"},
  {name: "benin", code: "BJ", url: "https://flagcdn.com/w320/bj.png"},
  {name: "bhutan", code: "BT", url: "https://flagcdn.com/w320/bt.png"},
  {name: "bolivia", code: "BO", url: "https://flagcdn.com/w320/bo.png"},
  {name: "bosnia-and-herzegovina", code: "BA", url: "https://flagcdn.com/w320/ba.png"},
  {name: "botswana", code: "BW", url: "https://flagcdn.com/w320/bw.png"},
  {name: "brazil", code: "BR", url: "https://flagcdn.com/w320/br.png"},
  {name: "brunei", code: "BN", url: "https://flagcdn.com/w320/bn.png"},
  {name: "bulgaria", code: "BG", url: "https://flagcdn.com/w320/bg.png"},
  {name: "burkina-faso", code: "BF", url: "https://flagcdn.com/w320/bf.png"},
  {name: "burundi", code: "BI", url: "https://flagcdn.com/w320/bi.png"},
  {name: "cabo-verde", code: "CV", url: "https://flagcdn.com/w320/cv.png"},
  {name: "cambodia", code: "KH", url: "https://flagcdn.com/w320/kh.png"},
  {name: "cameroon", code: "CM", url: "https://flagcdn.com/w320/cm.png"},
  {name: "canada", code: "CA", url: "https://flagcdn.com/w320/ca.png"},
  {name: "central-african-republic", code: "CF", url: "https://flagcdn.com/w320/cf.png"},
  {name: "chad", code: "TD", url: "https://flagcdn.com/w320/td.png"},
  {name: "chile", code: "CL", url: "https://flagcdn.com/w320/cl.png"},
  {name: "china", code: "CN", url: "https://flagcdn.com/w320/cn.png"},
  {name: "colombia", code: "CO", url: "https://flagcdn.com/w320/co.png"},
  {name: "comoros", code: "KM", url: "https://flagcdn.com/w320/km.png"},
  {name: "congo", code: "CG", url: "https://flagcdn.com/w320/cg.png"},
  {name: "costa-rica", code: "CR", url: "https://flagcdn.com/w320/cr.png"},
  {name: "croatia", code: "HR", url: "https://flagcdn.com/w320/hr.png"},
  {name: "cuba", code: "CU", url: "https://flagcdn.com/w320/cu.png"},
  {name: "cyprus", code: "CY", url: "https://flagcdn.com/w320/cy.png"},
  {name: "czechia", code: "CZ", url: "https://flagcdn.com/w320/cz.png"},
  {name: "democratic-republic-of-the-congo", code: "CD", url: "https://flagcdn.com/w320/cd.png"},
  {name: "denmark", code: "DK", url: "https://flagcdn.com/w320/dk.png"},
  {name: "djibouti", code: "DJ", url: "https://flagcdn.com/w320/dj.png"},
  {name: "dominica", code: "DM", url: "https://flagcdn.com/w320/dm.png"},
  {name: "dominican-republic", code: "DO", url: "https://flagcdn.com/w320/do.png"},
  {name: "east-timor", code: "TL", url: "https://flagcdn.com/w320/tl.png"},
  {name: "ecuador", code: "EC", url: "https://flagcdn.com/w320/ec.png"},
  {name: "egypt", code: "EG", url: "https://flagcdn.com/w320/eg.png"},
  {name: "el-salvador", code: "SV", url: "https://flagcdn.com/w320/sv.png"},
  {name: "equatorial-guinea", code: "GQ", url: "https://flagcdn.com/w320/gq.png"},
  {name: "eritrea", code: "ER", url: "https://flagcdn.com/w320/er.png"},
  {name: "estonia", code: "EE", url: "https://flagcdn.com/w320/ee.png"},
  {name: "eswatini", code: "SZ", url: "https://flagcdn.com/w320/sz.png"},
  {name: "ethiopia", code: "ET", url: "https://flagcdn.com/w320/et.png"},
  {name: "fiji", code: "FJ", url: "https://flagcdn.com/w320/fj.png"},
  {name: "finland", code: "FI", url: "https://flagcdn.com/w320/fi.png"},
  {name: "france", code: "FR", url: "https://flagcdn.com/w320/fr.png"},
  {name: "gabon", code: "GA", url: "https://flagcdn.com/w320/ga.png"},
  {name: "gambia", code: "GM", url: "https://flagcdn.com/w320/gm.png"},
  {name: "georgia", code: "GE", url: "https://flagcdn.com/w320/ge.png"},
  {name: "germany", code: "DE", url: "https://flagcdn.com/w320/de.png"},
  {name: "ghana", code: "GH", url: "https://flagcdn.com/w320/gh.png"},
  {name: "greece", code: "GR", url: "https://flagcdn.com/w320/gr.png"},
  {name: "grenada", code: "GD", url: "https://flagcdn.com/w320/gd.png"},
  {name: "guatemala", code: "GT", url: "https://flagcdn.com/w320/gt.png"},
  {name: "guinea", code: "GN", url: "https://flagcdn.com/w320/gn.png"},
  {name: "guinea-bissau", code: "GW", url: "https://flagcdn.com/w320/gw.png"},
  {name: "guyana", code: "GY", url: "https://flagcdn.com/w320/gy.png"},
  {name: "haiti", code: "HT", url: "https://flagcdn.com/w320/ht.png"},
  {name: "honduras", code: "HN", url: "https://flagcdn.com/w320/hn.png"},
  {name: "hungary", code: "HU", url: "https://flagcdn.com/w320/hu.png"},
  {name: "iceland", code: "IS", url: "https://flagcdn.com/w320/is.png"},
  {name: "india", code: "IN", url: "https://flagcdn.com/w320/in.png"},
  {name: "indonesia", code: "ID", url: "https://flagcdn.com/w320/id.png"},
  {name: "iran", code: "IR", url: "https://flagcdn.com/w320/ir.png"},
  {name: "iraq", code: "IQ", url: "https://flagcdn.com/w320/iq.png"},
  {name: "ireland", code: "IE", url: "https://flagcdn.com/w320/ie.png"},
  {name: "israel", code: "IL", url: "https://flagcdn.com/w320/il.png"},
  {name: "italy", code: "IT", url: "https://flagcdn.com/w320/it.png"},
  {name: "ivory-coast", code: "CI", url: "https://flagcdn.com/w320/ci.png"},
  {name: "jamaica", code: "JM", url: "https://flagcdn.com/w320/jm.png"},
  {name: "japan", code: "JP", url: "https://flagcdn.com/w320/jp.png"},
  {name: "jordan", code: "JO", url: "https://flagcdn.com/w320/jo.png"},
  {name: "kazakhstan", code: "KZ", url: "https://flagcdn.com/w320/kz.png"},
  {name: "kenya", code: "KE", url: "https://flagcdn.com/w320/ke.png"},
  {name: "kiribati", code: "KI", url: "https://flagcdn.com/w320/ki.png"},
  {name: "kosovo", code: "XK", url: "https://flagcdn.com/w320/xk.png"},
  {name: "kuwait", code: "KW", url: "https://flagcdn.com/w320/kw.png"},
  {name: "kyrgyzstan", code: "KG", url: "https://flagcdn.com/w320/kg.png"},
  {name: "laos", code: "LA", url: "https://flagcdn.com/w320/la.png"},
  {name: "latvia", code: "LV", url: "https://flagcdn.com/w320/lv.png"},
  {name: "lebanon", code: "LB", url: "https://flagcdn.com/w320/lb.png"},
  {name: "lesotho", code: "LS", url: "https://flagcdn.com/w320/ls.png"},
  {name: "liberia", code: "LR", url: "https://flagcdn.com/w320/lr.png"},
  {name: "libya", code: "LY", url: "https://flagcdn.com/w320/ly.png"},
  {name: "liechtenstein", code: "LI", url: "https://flagcdn.com/w320/li.png"},
  {name: "lithuania", code: "LT", url: "https://flagcdn.com/w320/lt.png"},
  {name: "luxembourg", code: "LU", url: "https://flagcdn.com/w320/lu.png"},
  {name: "madagascar", code: "MG", url: "https://flagcdn.com/w320/mg.png"},
  {name: "malawi", code: "MW", url: "https://flagcdn.com/w320/mw.png"},
  {name: "malaysia", code: "MY", url: "https://flagcdn.com/w320/my.png"},
  {name: "maldives", code: "MV", url: "https://flagcdn.com/w320/mv.png"},
  {name: "mali", code: "ML", url: "https://flagcdn.com/w320/ml.png"},
  {name: "malta", code: "MT", url: "https://flagcdn.com/w320/mt.png"},
  {name: "marshall-islands", code: "MH", url: "https://flagcdn.com/w320/mh.png"},
  {name: "mauritania", code: "MR", url: "https://flagcdn.com/w320/mr.png"},
  {name: "mauritius", code: "MU", url: "https://flagcdn.com/w320/mu.png"},
  {name: "mexico", code: "MX", url: "https://flagcdn.com/w320/mx.png"},
  {name: "micronesia", code: "FM", url: "https://flagcdn.com/w320/fm.png"},
  {name: "moldova", code: "MD", url: "https://flagcdn.com/w320/md.png"},
  {name: "monaco", code: "MC", url: "https://flagcdn.com/w320/mc.png"},
  {name: "mongolia", code: "MN", url: "https://flagcdn.com/w320/mn.png"},
  {name: "montenegro", code: "ME", url: "https://flagcdn.com/w320/me.png"},
  {name: "morocco", code: "MA", url: "https://flagcdn.com/w320/ma.png"},
  {name: "mozambique", code: "MZ", url: "https://flagcdn.com/w320/mz.png"},
  {name: "myanmar", code: "MM", url: "https://flagcdn.com/w320/mm.png"},
  {name: "namibia", code: "NA", url: "https://flagcdn.com/w320/na.png"},
  {name: "nauru", code: "NR", url: "https://flagcdn.com/w320/nr.png"},
  {name: "nepal", code: "NP", url: "https://flagcdn.com/w320/np.png"},
  {name: "netherlands", code: "NL", url: "https://flagcdn.com/w320/nl.png"},
  {name: "new-zealand", code: "NZ", url: "https://flagcdn.com/w320/nz.png"},
  {name: "nicaragua", code: "NI", url: "https://flagcdn.com/w320/ni.png"},
  {name: "niger", code: "NE", url: "https://flagcdn.com/w320/ne.png"},
  {name: "nigeria", code: "NG", url: "https://flagcdn.com/w320/ng.png"},
  {name: "north-korea", code: "KP", url: "https://flagcdn.com/w320/kp.png"},
  {name: "north-macedonia", code: "MK", url: "https://flagcdn.com/w320/mk.png"},
  {name: "norway", code: "NO", url: "https://flagcdn.com/w320/no.png"},
  {name: "oman", code: "OM", url: "https://flagcdn.com/w320/om.png"},
  {name: "pakistan", code: "PK", url: "https://flagcdn.com/w320/pk.png"},
  {name: "palau", code: "PW", url: "https://flagcdn.com/w320/pw.png"},
  {name: "palestine", code: "PS", url: "https://flagcdn.com/w320/ps.png"},
  {name: "panama", code: "PA", url: "https://flagcdn.com/w320/pa.png"},
  {name: "papua-new-guinea", code: "PG", url: "https://flagcdn.com/w320/pg.png"},
  {name: "paraguay", code: "PY", url: "https://flagcdn.com/w320/py.png"},
  {name: "peru", code: "PE", url: "https://flagcdn.com/w320/pe.png"},
  {name: "philippines", code: "PH", url: "https://flagcdn.com/w320/ph.png"},
  {name: "poland", code: "PL", url: "https://flagcdn.com/w320/pl.png"},
  {name: "portugal", code: "PT", url: "https://flagcdn.com/w320/pt.png"},
  {name: "qatar", code: "QA", url: "https://flagcdn.com/w320/qa.png"},
  {name: "romania", code: "RO", url: "https://flagcdn.com/w320/ro.png"},
  {name: "russia", code: "RU", url: "https://flagcdn.com/w320/ru.png"},
  {name: "rwanda", code: "RW", url: "https://flagcdn.com/w320/rw.png"},
  {name: "saint-kitts-and-nevis", code: "KN", url: "https://flagcdn.com/w320/kn.png"},
  {name: "saint-lucia", code: "LC", url: "https://flagcdn.com/w320/lc.png"},
  {name: "saint-vincent-and-the-grenadines", code: "VC", url: "https://flagcdn.com/w320/vc.png"},
  {name: "samoa", code: "WS", url: "https://flagcdn.com/w320/ws.png"},
  {name: "san-marino", code: "SM", url: "https://flagcdn.com/w320/sm.png"},
  {name: "sao-tome-and-principe", code: "ST", url: "https://flagcdn.com/w320/st.png"},
  {name: "saudi-arabia", code: "SA", url: "https://flagcdn.com/w320/sa.png"},
  {name: "senegal", code: "SN", url: "https://flagcdn.com/w320/sn.png"},
  {name: "serbia", code: "RS", url: "https://flagcdn.com/w320/rs.png"},
  {name: "seychelles", code: "SC", url: "https://flagcdn.com/w320/sc.png"},
  {name: "sierra-leone", code: "SL", url: "https://flagcdn.com/w320/sl.png"},
  {name: "singapore", code: "SG", url: "https://flagcdn.com/w320/sg.png"},
  {name: "slovakia", code: "SK", url: "https://flagcdn.com/w320/sk.png"},
  {name: "slovenia", code: "SI", url: "https://flagcdn.com/w320/si.png"},
  {name: "solomon-islands", code: "SB", url: "https://flagcdn.com/w320/sb.png"},
  {name: "somalia", code: "SO", url: "https://flagcdn.com/w320/so.png"},
  {name: "south-africa", code: "ZA", url: "https://flagcdn.com/w320/za.png"},
  {name: "south-korea", code: "KR", url: "https://flagcdn.com/w320/kr.png"},
  {name: "south-sudan", code: "SS", url: "https://flagcdn.com/w320/ss.png"},
  {name: "spain", code: "ES", url: "https://flagcdn.com/w320/es.png"},
  {name: "sri-lanka", code: "LK", url: "https://flagcdn.com/w320/lk.png"},
  {name: "sudan", code: "SD", url: "https://flagcdn.com/w320/sd.png"},
  {name: "suriname", code: "SR", url: "https://flagcdn.com/w320/sr.png"},
  {name: "sweden", code: "SE", url: "https://flagcdn.com/w320/se.png"},
  {name: "switzerland", code: "CH", url: "https://flagcdn.com/w320/ch.png"},
  {name: "syria", code: "SY", url: "https://flagcdn.com/w320/sy.png"},
  {name: "taiwan", code: "TW", url: "https://flagcdn.com/w320/tw.png"},
  {name: "tajikistan", code: "TJ", url: "https://flagcdn.com/w320/tj.png"},
  {name: "tanzania", code: "TZ", url: "https://flagcdn.com/w320/tz.png"},
  {name: "thailand", code: "TH", url: "https://flagcdn.com/w320/th.png"},
  {name: "togo", code: "TG", url: "https://flagcdn.com/w320/tg.png"},
  {name: "tonga", code: "TO", url: "https://flagcdn.com/w320/to.png"},
  {name: "trinidad-and-tobago", code: "TT", url: "https://flagcdn.com/w320/tt.png"},
  {name: "tunisia", code: "TN", url: "https://flagcdn.com/w320/tn.png"},
  {name: "turkey", code: "TR", url: "https://flagcdn.com/w320/tr.png"},
  {name: "turkmenistan", code: "TM", url: "https://flagcdn.com/w320/tm.png"},
  {name: "tuvalu", code: "TV", url: "https://flagcdn.com/w320/tv.png"},
  {name: "uganda", code: "UG", url: "https://flagcdn.com/w320/ug.png"},
  {name: "ukraine", code: "UA", url: "https://flagcdn.com/w320/ua.png"},
  {name: "united-arab-emirates", code: "AE", url: "https://flagcdn.com/w320/ae.png"},
  {name: "united-kingdom", code: "GB", url: "https://flagcdn.com/w320/gb.png"},
  {name: "united-states", code: "US", url: "https://flagcdn.com/w320/us.png"},
  {name: "uruguay", code: "UY", url: "https://flagcdn.com/w320/uy.png"},
  {name: "uzbekistan", code: "UZ", url: "https://flagcdn.com/w320/uz.png"},
  {name: "vanuatu", code: "VU", url: "https://flagcdn.com/w320/vu.png"},
  {name: "vatican-city", code: "VA", url: "https://flagcdn.com/w320/va.png"},
  {name: "venezuela", code: "VE", url: "https://flagcdn.com/w320/ve.png"},
  {name: "vietnam", code: "VN", url: "https://flagcdn.com/w320/vn.png"},
  {name: "yemen", code: "YE", url: "https://flagcdn.com/w320/ye.png"},
  {name: "zambia", code: "ZM", url: "https://flagcdn.com/w320/zm.png"},
  {name: "zimbabwe", code: "ZW", url: "https://flagcdn.com/w320/zw.png"}
]
export { words, countryFlagsImg };